Prevent HTTP 500 errors during install process
Error: PHP Fatal error:  require_once(): Failed opening required 'footer-credit/footer-credit.php' (include_path='.:/usr/share/php:/usr/share/pear') in /www/https_nylen.io/jp/wp-content/mu-plugins/wpcomsh/wpcomsh.php on line 18, referer: https://nylen.io/jp/wp-admin/edit.php

This happens because the wpcomsh-loader is activated before wpcomsh dependencies are installed.  To fix this, make sure dependencies are installed before trying to load wpcomsh.